### ISSUE TITLE
sjasmplus: implement OPT directives used by SpecNext Invaders

### ISSUE THREAD

**Issue by stevehill1981** [asm198x/asm198x#431]
## Evidence

The pinned `howprice/specnext-invaders` game builds with SjASMPlus 1.21.0, but Asm198x rejects its first line of assembler configuration.

Pinned source: https://github.com/howprice/specnext-invaders/tree/e3211ea8ad2e83aca4d07d70bd8e09b7b51a9a1d

Native control:

```sh
sjasmplus --fullpath --sld=bin/invaders.sld --lst=bin/invaders.lst --lstlab --sym=bin/invaders.labels --msg=war src/main.asm
```

This succeeds and writes `bin/invaders.nex`. Asm198x reports:

```text
src/main.asm:4: error: `OPT` is a directive this dialect has and asm198x does not implement
```

## Expected

Asm198x implements the `OPT` forms used by the project with SjASMPlus-compatible semantics. Options that affect parsing or emitted bytes must take effect; options irrelevant to Asm198x output may be accepted only after reference probing establishes that dropping them is harmless.

## Acceptance

- Identify and probe every `OPT` form used by the pinned target.
- Add differential tests for byte-affecting behavior and explicit tests for safely inert options.
- Keep option state scoped exactly as SjASMPlus scopes it.
- The `howprice-specnext-invaders` corpus target no longer stops at `OPT`; later independent gaps may surface normally.

Broader SjASMPlus parity tracker: #275.

Corpus decision and initial audit: https://github.com/asm198x/asm198x/blob/main/decisions/ecosystem-source-corpus.md and https://github.com/asm198x/asm198x/blob/main/docs/ecosystem-corpus.md
